// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZwexCqDMHxt_V4G-CuYa-AQ7wawvDa0',
    appId: '1:987360038156:web:71261c3b101b22f98f0d29',
    messagingSenderId: '987360038156',
    projectId: 'smart-task-planner-5b428',
    authDomain: 'smart-task-planner-5b428.firebaseapp.com',
    storageBucket: 'smart-task-planner-5b428.firebasestorage.app',
    measurementId: 'G-WXDB3KHK7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1hB6e5PETZr2wEutpXXnASEMseg9REzc',
    appId: '1:987360038156:android:3fef8a39aee3aaaa8f0d29',
    messagingSenderId: '987360038156',
    projectId: 'smart-task-planner-5b428',
    storageBucket: 'smart-task-planner-5b428.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIUdBGvPqpWJWaFIXooozZpfo_db6mbU',
    appId: '1:987360038156:ios:c2697d845be5ae218f0d29',
    messagingSenderId: '987360038156',
    projectId: 'smart-task-planner-5b428',
    storageBucket: 'smart-task-planner-5b428.firebasestorage.app',
    iosBundleId: 'com.smartplanner.smartTaskTimetablePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaIUdBGvPqpWJWaFIXooozZpfo_db6mbU',
    appId: '1:987360038156:ios:c2697d845be5ae218f0d29',
    messagingSenderId: '987360038156',
    projectId: 'smart-task-planner-5b428',
    storageBucket: 'smart-task-planner-5b428.firebasestorage.app',
    iosBundleId: 'com.smartplanner.smartTaskTimetablePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDZwexCqDMHxt_V4G-CuYa-AQ7wawvDa0',
    appId: '1:987360038156:web:55a6ed432a8dd6e08f0d29',
    messagingSenderId: '987360038156',
    projectId: 'smart-task-planner-5b428',
    authDomain: 'smart-task-planner-5b428.firebaseapp.com',
    storageBucket: 'smart-task-planner-5b428.firebasestorage.app',
    measurementId: 'G-GYBKN548XN',
  );
}
